[package]
name = "dotenvx-rs"
version = "0.1.0"
edition = "2024"
authors = ["linux_china <libing.chen@gmail.com>"]
description = "Dotenvx is a Rust command-line/library to encrypt your .env files - limiting their attack vector while retaining their benefits"
keywords = ["dotenv", "dotenvx", "secret", "vault"]
categories = ["command-line-utilities"]
documentation = "https://github.com/linux-china/dotenvx-rs"
readme = "README.md"
homepage = "https://github.com/linux-china/dotenvx-rs"
repository = "https://github.com/linux-china/dotenvx-rs"
license = "MIT"


[[bin]]
name = "dotenvx"
path = "src/main.rs"

[dependencies]
base64 = "0.22.1"
clap = "4.5.41"
dotenvy = "0.15.7"
ecies = { version = "0.2", features = ["std"] }
hex = "0.4.3"
dirs = "6"
colored = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored_json = "5"
walkdir = "2.5.0"
openssl = { version = "0.10", features = ["vendored"] }

[profile.dev]
opt-level = 0
debug = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
